import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CartProvider from "@/app/cartContext/createContext";

const geistSans = localFont({
  src: "./fonts/HelveticaNeueMedium.otf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/HelveticaNeueMedium.otf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider> {children}</CartProvider>
      </body>
    </html>
  );
}
